const translations = {
    ko: {
        "index_button_introduce" : "아뜰리에 노들 소개",
        "index_button_schedule" : "전시 시간표",
        "index_button_exhibit" : "빛이 꾸는 꿈",
        "index_button_exhibit_sub" : "Dreams Dreamed by Light",
        "index_button_art_1" : "동행 모먼트서울",
        "index_button_art_1_sub" : "Moment Seoul",
        "index_button_art_2" : "매력 한강네이처",
        "index_button_art_2_sub" : "Hangang Nature",
        "index_button_directions" : "오시는 길",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        "atelier_nodeul_name" : "아뜰리에 노들",
        "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<아뜰리에 노들 2026 두 번째 전시 : 빛이 꾸는 꿈> 상영 시간표",
        "schedule_explain_date" : "전시 기간: 2026.09.01.(화) ~ 2026.10.31.(토)",
        "schedule_explain_pos" : "상영 장소: 노들섬 남단 한강대교 교각 하부 미디어파사드",
        "schedule_explain_pos_detail" : "노들섬 아트라운지 미디어볼 상명 시간",
        "schedule_explain_time" : "상영 시간: 19:00 ~ 23:00 (매 시각 정시 상영)",
        "schedule_explain_time_detail" : "",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        "exhibit_intro_title" : "전시 소개",        
        "exhibit_introduce_name" : "2026 아뜰리에 노들 두 번째 전시 : 빛이 꾸는 꿈\nAtelier Nodeul 2026 2nd Exhibition : Dreams Dreamed by Light",
        "exhibit_introduce" : "토마스 헤더윅의 〈소리풍경(Soundscape)〉프로젝트와 함께 개장한 [아뜰리에 노들]의 2026년 두 번째 전시가 개최됩니다.\n\n이번 전시는 '2026 서울라이트 한강 빛섬축제'와 연계해 빛과 예술, 자연과 시민의 경험을 아우르는 예술, 동행, 매력 세 가지 섹션으로 구성됩니다.\n\n예술 섹션 '빛이 꾸는 꿈(Dreams Dreamed by Light)'에서는 미디어 아티스트 박제성과 장승효가 참여해 빛과 디지털 기술로 확장되는 꿈과 현실의 경계, 인간과 자연, 기술과 감성이 연결되는 미래적 풍경을 선보입니다.\n동행 섹션인 모먼트 서울(Moment Seoul)은 시민들이 지나온 시간의 의미를 따뜻하게 되돌아볼 수 있도록 위로와 공감의 메시지를 전하며, 서울의 상징 캐릭터 해치와 소울프렌즈가 함께하는 가을 나들이를 통해 일상 속 작은 즐거움을 전합니다. 매력 섹션 한강 네이처(Hangang Nature)는 노들섬의 깃대종인 맹꽁이를 중심으로 한강의 생태와 계절의 변화를 친근한 이야기로 풀어내며, 도시와 자연이 공존하는 노들의 숨은 매력을 조명합니다.\n\n*예술 : 빛이 꾸는 꿈 (Dreams Dreamed by Light)\n*동행 : 모먼트 서울 (Moment Seoul)\n*매력 : 한강 네이처 (Hangang Nature)",
        "exhibit_introduce_sub" : "*특정 지역이나 환경을 대표하면서 사람들의 관심과 보호의식을 이끌어내기 위해 선정된 상징적인 생물종",
        "exhibit_explain_name_1" : "빛이 꾸는 꿈",
        "exhibit_explain_1" : "'빛이 꾸는 꿈 Dreams Dreamed by Light’을 주제로 한 예술 섹션은 박제성과 장승효 두 미디어 아티스트의 작품을 통해 꿈과 현실, 인간과 기술, 자연과 문명이 연결되는 미래적 풍경을 선보입니다. AI와 가상공간을 통해 인간의 감각과 존재를 탐구하는 박제성의 작품과, 백남준 · 가우디의 정신을 디지털 기술로 확장한 장승효의 작품은 빛 속에서 펼쳐지는 새로운 상상과 예술적 가능성을 제시합니다.",
        "exhibit_explain_name_2" : "모먼트 서울",
        "exhibit_explain_2" : "'동행(Moment Seoul)에서는 서울의 핵심 가치인 '약자와 동행하는 상생 도시'를 바탕으로 시민의 일상에 따뜻한 빛을 더합니다.\n 〈당신의 빛나는 모든 계절〉을 통해 각자의 자리에서 묵묵히 살아가는 시민들에게 위로와 응원의 메시지를 전하고, 〈해치와 서울나들이〉는 일월오봉도 속 세상을 벗어난 해치와 소울프렌즈가 서울의 가을 풍경 속에서 펼치는 즐거운 여정을 선보입니다.",
        "exhibit_explain_name_3" : "한강 네이처",
        "exhibit_explain_3" : "'한강 네이처(Hangang Nature)'는 서울의 비전인 ‘매력’을 상징하며, 자연이 살아 숨 쉬는 한강 노들섬의 생태를 미디어아트로 풀어낸 자연도감입니다.\n 맹꽁이를 주인공으로 한 옴니버스 애니메이션으로, 새로운 터전을 찾아가는 여정을 통해 노들섬의 생태와 계절의 변화, 그리고 서울과 한강의 다양한 모습을 전합니다.",
        
        "link_button_text" : "영상 보러가기",

        "exhibit_name_1" : "예술\n빛이 꾸는 꿈\n(Dreams Dreamed by Light)",
        "exhibit_name_2" : "동행\n모먼트서울\n(Moment Seoul)",        
        "exhibit_name_3" : "매력\n한강 네이쳐\n(Hangang Nature)",

        "art_name_1" : "작품명1",
        "art_name_2" : "작품명2",
        "art_name_3" : "작품명3",
        
        "exhibit_list_1" : "몽유 50806202",
        "exhibit_list_2" : "유니버스",
        "exhibit_list_3" : "가우디 하늘을 날다",
        "exhibit_list_4" : "남준쇼와 쇼니 가우디의 만남 - \n하나되기",
        "exhibit_list_5" : "",
        "exhibit_list_6" : "",
        "exhibit_list_7" : "당신의 빛나는 모든 계절",
        "exhibit_list_8" : "해치와 서울나들이",
        "exhibit_list_9" : "꼬마 맹꽁이의 모험",

        "art_list_1" : "몽유 50806202",
        "art_list_2" : "유니버스",
        "art_list_3" : "가우디 하늘을 날다",
        "art_list_4" : "남준쇼와 쇼니 가우디의 만남 – 하나되기",
        "art_list_5" : "",
        "art_list_6" : "",
        "art_list_7" : "당신의 빛나는 모든 계절",
        "art_list_8" : "해치와 서울 나들이",
        "art_list_9" : "꼬마 맹꽁이의 모험",

        "artist_name_1" : "박제성",
        "artist_name_2" : "박제성",
        "artist_name_3" : "장승효",
        "artist_name_4" : "장승효",
        "artist_name_5" : "",
        "artist_name_6" : "",
        "artist_name_7" : "",
        "artist_name_8" : "",
        "artist_name_9" : "",

        "art_explain_1" : "도시를 오가는 사람들의 모습을 나비의 꿈속 풍경으로 재해석한 작품입니다.\n\n장자의 호접몽 속 나비와 인간의 관계를 오늘날 인간과 기술의 관계로 풀어내며, 꿈과 현실의 경계 너머에서 우리가 인식하는 세계와 존재의 의미를 새롭게 질문합니다.",
        "art_explain_2" : "인간의 알고리듬화된 감정을 초현실적 가상공간에 재현한 작품입니다. 화려한 놀이기구가 결합된 기계장치는 텅 빈 공간을 부유하며 윤회를 상징하듯 끝없이 궤도를 돕니다.\n\n <유니버스>는 쾌락과 공포라는 양 극단의 자극을 좇는 현대인의 삶을 비추는 동시에, 기술과 인간의 관계 및 인간 고유의 영역이라고 할 수 있는 '감정'이란 무엇인가에 대해 질문하며, 아름다움과 불안이 공존하는 독특한 감각적 경험을 선사합니다.",
        "art_explain_3" : "'안토니 가우디가 꿈꾸었던 자연과 문명의 조화로운 세계가 펼쳐지고, 다시 태어난 '쇼니 가우디'가 상징적 존재인 고래의 모습으로 그 하늘을 날아다니는 형상을 묘사합니다.\n\n〈가우디 하늘을 날다〉는 자연의 원리와 아름다움을 건축에 담고자 했던 가우디의 시선을 바탕으로, 자연과 문명이 공존하는 새로운 풍경을 보여주며 오늘날 우리가 겪고 있는 인간과 자연의 공존에 대한 새로운 시선을 제시합니다.",
        "art_explain_4" : "<남준쇼와 쇼니 가우디의 만남 - 하나되기>는 2026년 가우디 서거 100주년을 기념해, 백남준이 AI 메타휴먼으로 재탄생해 가우디와 조우하는 미래적 상상을 펼칩니다. 다중우주를 여행한 두 존재는 모든 것이 서로 연결되고 중첩되어 있으며, 하나에서 시작해 다시 하나로 귀결된다는 깨달음에 도달합니다.\n\n두 예술가의 시공간을 초월한 만남과 디지털 기술의 융합을 통해 AI시대를 살아가는 이들에게 '하나됨'을 이야기합니다.",
        "art_explain_4_sub" : "",
        "art_explain_5" : "",
        "art_explain_6" : "",
        "art_explain_7" : "누구나 마음속 작은 빛으로 간직해온 희망을 응원하며, 당신이 지나온 모든 시간이 저마다 빛나는 계절이었음을 전하는 따뜻한 메시지를 전합니다.",
        "art_explain_8" : "해치와 친구들의 가을 나들이 대작전을 그린 작품입니다.\n\n미술관의 일월오봉도 속 오브제가 된 해치와 소울프렌즈는 단풍잎을 타고 서울의 가을 풍경 속으로 나들이를 떠납니다. 마침내 서울라이트 한강 빛섬축제에 도착해 빛의 향연을 즐깁니다.",
        "art_explain_9" : "무당벌레의 화려한 빛에 이끌린 꼬마 맹꽁이 ‘노들이’는 가을빛으로 물든 식물들을 징검다리 삼아 울창한 노들섬 습지 숲으로 모험을 떠납니다.\n\n숲을 여행하던 노들이는 다정한 백로에게 하얀 구절초를 선물받고, 마침내 아름다운 구절초 꽃밭에 도착해 평화로운 휴식을 맞이합니다.",

        "time_table_title" : "전시 순서 안내",
        "time_table_title_1" : "예술",
        "time_table_title_2" : "동행",
        "time_table_title_3" : "매력",
        "time_table_title_sub_1" : "빛이 꾸는 꿈",
        "time_table_title_sub_2" : "모먼트 서울",
        "time_table_title_sub_3" : "한강 네이처",
        "time_table_art_1" : "1. 박제성 〈몽유 50806202〉",
        "time_table_art_2" : "2. 장승효 〈가우디 하늘을 날다〉", 
        "time_table_art_3" : "",
        "time_table_art_4" : "3. 당신의 빛나는 모든 계절",
        "time_table_art_5" : "4. 해치와 서울나들이",
        "time_table_art_6" : "5. 꼬마 맹꽁이의 모험",
        "time_table_art_7" : "6. 박제성 〈유니버스〉",
        "time_table_art_8" : "7. 장승효 〈남준쇼와 쇼니 가우디의 만남 - \n하나되기〉",
        "time_table_art_9" : "",
        "time_table_art_10" : "8. 당신의 빛나는 모든 계절",
        "time_table_art_11" : "9. 해치와 서울나들이",
        "time_table_art_12" : "10. 꼬마 맹꽁이의 모험",

        "directions_title" : "오시는 길",
        "directions_map_title_1" : "노들섬 서측에서 오실 경우",
        "directions_map_title_2" : "노들섬 동측에서 오실 경우",

        "directions_explain_title_1" : "지하철",
        "directions_explain_title_2" : "버스",
        "directions_explain_title_3" : "한강 버스",

        "directions_explain_1" : "1호선\n용산역 5번 출구 → 신용산역 정류장(03-004) 승차 → 노들섬 버스정류장 하차\n\n4호선\n신용산역 3번 출구 → 신용산역 정류장(03-004) 승차 → 노들섬 버스정류장 하차\n\n9호선\n노들역 2번 출구 → 한강대교 방면 도보 약 700m\n\n\n",
        "directions_explain_2" : "간선 버스\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752\n\n지선버스\n6211\n\n",
        "directions_explain_3" : "여의도 - 압구정 사이 구간에서 관람 가능",
    },
    en : {
        "index_button_introduce" : "Atelier Nodeul Introduction",
        "index_button_schedule" : "Schedule",
        "index_button_exhibit" : "Art",
        "index_button_exhibit_sub" : "Dreams Dreamed by Light",
        "index_button_art_1" : "Companion ",
        "index_button_art_1_sub" : " Moment Seoul",
        "index_button_art_2" : "Charmy",
        "index_button_art_2_sub" : " Hangang Nature",
        "index_button_directions" : "Location",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        "atelier_nodeul_name" : "아뜰리에 노들",
        "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<Atelier Nodeul 2026 2nd Exhibition : Dreams Dreamed by Light> Timeline",
        "schedule_explain_date" : "Exhibition Period | Sep 01, 2026 (Tue) – Oct 31, 2026 (Sat)",
        "schedule_explain_pos" : "Venue | Media Façade under the southern pier of Hangang Bridge,\n             Nodeul Island",
        "schedule_explain_pos_detail" : "",
        "schedule_explain_time" : "Screening Hours | 19:00–23:00 (Screened every hour on the hour)",
        "schedule_explain_time_detail" : "",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        "exhibit_intro_title" : "Exhibition Introduction",        
        "exhibit_introduce_name" : "Atelier Nodeul 2026 2ND EXHIBITION : Dreams Dreamed by Light",
        "exhibit_introduce" : "Atelier Nodeul, which opened in conjunction with Thomas Heatherwick’s 〈Soundscape〉 project, presents its second exhibition of 2026.\n\nHeld in connection with the 2026 Seoul Light Hangang Bitseom Festival, the exhibition brings together light, art, nature, and the experiences of citizens across three sections: Art, Companion, and Charmy.\n\nThe Art section, 'Dreams Dreamed by Light,' features media artists Je Baak and Jang SeungHyo. Through light and digital technology, their works present futuristic visions in which the boundaries between dreams and reality expand, and connections emerge between humanity and nature, technology and emotion.\n\nThe Companion section, 'Moment Seoul,' offers messages of comfort and empathy, inviting citizens to warmly reflect on the meaning of the time they have lived through. It also brings moments of everyday joy through an autumn outing with Seoul’s symbolic character Hechi and the Soul Friends.\n\nThe Charmy section, 'Hangang Nature,' tells an engaging story about the Hangang River’s ecosystem and seasonal changes through the Mengkongi, Nodeul Island’s flagship species. It highlights the lesser-known charms of Nodeul, where the city and nature coexist.\n\nArt: Dreams Dreamed by Light\nCompanion: Moment Seoul\nCharmy: Hangang Nature",
        "exhibit_introduce_sub" : "",
        "exhibit_explain_name_1" : "Dreams Dreamed by Light",
        "exhibit_explain_1" : "Under the theme “Dreams Dreamed by Light,” the Art section presents futuristic visions in which dreams and reality, humanity and technology, and nature and civilization are interconnected through works by media artists Je Baak and Jang SeungHyo.\n\nJe Baak explores human perception and existence through AI and virtual spaces, while Jang SeungHyo expands the artistic visions of Nam June Paik and Antoni Gaudí through digital technology. Together, their works propose new realms of imagination and artistic possibility unfolding within light.",
        "exhibit_explain_name_2" : "Moment Seoul",
        "exhibit_explain_2" : "'The Companion section, “Moment Seoul,” brings warmth to citizens’ everyday lives, reflecting Seoul’s core value of building a city of shared growth that stands with the vulnerable.\n\n‘Messages of All Your Shining Seasons from Seoul’ offers messages of comfort and encouragement to citizens who quietly carry on in their own lives. In ‘Hechi’s Seoul Journey’, Hechi and the Soul Friends step out of the world of Irworobongdo and embark on a joyful adventure through Seoul’s autumn scenery.",
        "exhibit_explain_name_3" : "Hangang Nature",
        "exhibit_explain_3" : "“Hangang Nature” represents Seoul’s vision of “Charmy” and serves as a media art field guide to the living ecosystem of Nodeul Island on the Hangang River.\n\nThis omnibus animation follows a Mengkongi in search of a new home, introducing the ecology and seasonal changes of Nodeul Island as well as the diverse landscapes of Seoul and the Hangang River.",
        
        "link_button_text" : "Watch Video",

        "exhibit_name_1" : "Art\nDreams Dreamed by Light",
        "exhibit_name_2" : "Companion\nMoment Seoul",
        "exhibit_name_3" : "Charmy\nHangang Nature",

        "art_name_1" : "작품명1",
        "art_name_2" : "작품명2",
        "art_name_3" : "작품명3",
        
        "exhibit_list_1" : "MongYoo 50806202",
        "exhibit_list_2" : "Universe",
        "exhibit_list_3" : "Flying in the world of Gaudi",
        "exhibit_list_4" : "NamJune SHO meets SHONI Gaudi – Becoming One",
        "exhibit_list_5" : "",
        "exhibit_list_6" : "",
        "exhibit_list_7" : "Message of All Your Shining Seasons from Seoul",
        "exhibit_list_8" : "Hechi's Seoul Journey",
        "exhibit_list_9" : "Little Mengkongi’s Adventure",

        "art_list_1" : "MongYoo 50806202",
        "art_list_2" : "Universe",
        "art_list_3" : "Flying in the world of Gaudi",
        "art_list_4" : "NamJune SHO meets SHONI Gaudi - Becoming One",
        "art_list_5" : "",
        "art_list_6" : "",
        "art_list_7" : "Messages of All Your Shining Seasons from Seoul",
        "art_list_8" : "Hechi’s Seoul Journey",
        "art_list_9" : "Little Mengkongi’s Adventure",

        "artist_name_1" : "Je Baak",
        "artist_name_2" : "Je Baak",
        "artist_name_3" : "Jang SeungHyo",
        "artist_name_4" : "Jang SeungHyo",
        "artist_name_5" : "",
        "artist_name_6" : "",
        "artist_name_7" : "",
        "artist_name_8" : "",
        "artist_name_9" : "",

        "art_explain_1" : "'MongYoo' reimagines people moving through the city as figures within the landscape of a butterfly’s dream.\n\nDrawing on the relationship between the butterfly and the human in Zhuangzi’s \"Butterfly Dream\", the work reframes it through the contemporary relationship between humanity and technology. Beyond the boundaries of dreams and reality, it invites us to reconsider the world we perceive and the meaning of our existence.",
        "art_explain_2" : "'Universe' recreates algorithmically structured human emotions within a surreal virtual space.\n\nA mechanical structure composed of dazzling amusement park rides floats through an empty space, endlessly circling as if symbolizing the cycle of reincarnation. Reflecting modern life’s pursuit of the opposing extremes of pleasure and fear, the work raises questions about the relationship between humanity and technology, as well as the nature of emotion as a uniquely human realm. It offers a distinctive sensory experience in which beauty and unease coexist.",
        "art_explain_3" : "A harmonious world of nature and civilization envisioned by Antoni Gaudí unfolds as the reborn SHONI Gaudi takes the form of a symbolic whale and soars through its skies.\n\n'Flying in the world of Gaudi' draws on Gaudí’s vision of bringing the principles and beauty of nature into architecture. By presenting a new landscape where nature and civilization coexist, the work offers a fresh perspective on the relationship between humanity and nature today.",
        "art_explain_4" : "'NamJune SHO Meets SHONI Gaudi – Becoming One’ presents a futuristic vision in which Nam June Paik is reborn as an AI metahuman and encounters Antoni Gaudí, commemorating the centenary of Gaudí’s death in 2026.\n\nHaving journeyed through the multiverse, the two beings come to understand that everything is interconnected and overlapping, originating from one and ultimately returning to one. Through the timeless encounter between the two artists and its fusion with digital technology, the work conveys the meaning of “becoming one” to those living in the age of AI.",
        "art_explain_4_sub" : "* It refers to a medium through which light is transmitted, also understood as energy. In ancient Greek philosophy, it was considered one of the five elements, along with fire, water, air, and earth.",
        "art_explain_5" : "",
        "art_explain_6" : "",
        "art_explain_7" : " It delivers a warm message of encouragement for the hope that each of us carries as a small light within, reminding you that every season of your journey has shone in its own way.",
        "art_explain_8" : "This work follows Hechi and the Soul Friends on their grand autumn outing adventure.\n\nHaving become figures within an Irworobongdo painting in a museum, Hechi and the Soul Friends ride on autumn leaves and set out to explore Seoul’s fall scenery. They finally arrive at the Seoul Light Hangang Bitseom Festival, where they enjoy a spectacular celebration of light.",
        "art_explain_9" : "Drawn by the dazzling light of a ladybug, the little Mengkongi named Nodeuli uses autumn-colored plants as stepping stones and sets out on an adventure into a lush wetland forest.\n\nWhile exploring the forest, Nodeuli receives a white gujeolcho flower from a gentle egret. At last, Nodeuli arrives at a beautiful field of gujeolcho flowers and enjoys a peaceful rest.",

        "time_table_title" : "Information",
        "time_table_title_1" : "Art",
        "time_table_title_2" : "Companion",
        "time_table_title_3" : "Charmy",
        "time_table_title_sub_1" : "Dreams\nDreamed by Light",
        "time_table_title_sub_2" : "Moment Seoul",
        "time_table_title_sub_3" : "Hangang Nature",
        "time_table_art_1" : "1. Je Baak 〈MongYoo 50806202〉",
        "time_table_art_2" : "2. Jang SeungHyo 〈Flying in the world of Gaudi〉",
        "time_table_art_3" : "",
        "time_table_art_4" : "3. Messages of All Your Shining Seasons from Seoul",
        "time_table_art_5" : "4. Hechi’s Seoul Journey",
        "time_table_art_6" : "5. Little Mengkongi’s Adventure",
        "time_table_art_7" : "6. Je Baak 〈Universe〉",
        "time_table_art_8" : "7. Jang SeungHyo 〈NamJune SHO meets SHONI Gaudi - Becoming One〉",
        "time_table_art_9" : "",
        "time_table_art_10" : "8. Messages of All Your Shining Seasons from Seoul",
        "time_table_art_11" : "9. Hechi’s Seoul Journey",
        "time_table_art_12" : "10. Little Mengkongi’s Adventure",

        "directions_title" : "Location",
        "directions_map_title_1" : "From the West Side of Nodeul Island",
        "directions_map_title_2" : "From the East Side of Nodeul Island",

        "directions_explain_title_1" : "Subway",
        "directions_explain_title_2" : "Bus",
        "directions_explain_title_3" : "Hangang Bus",

        "directions_explain_1" : "Line 1\nYongsan Station Exit 5 → Bus from Sinyongsan Station(03-004) → Nodeul Island Bus Stop\n\nLine 4\nSinyongsan Station Exit 3 → Bus from Sinyongsan Station(03-004) → Nodeul Island Bus Stop\n\nLine 9\nNodeul Station Exit 2 → sWalk approx. 700m toward Hangang Bridge\n",
        "directions_explain_2" : "Blue Bus\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752\n\nGreen Bus\n6211",
        "directions_explain_3" : "The exhibition is visible while riding between Yeouido and Apgujeong.",
    },
    ja : {
        "index_button_introduce" : "(일본어)아뜰리에 노들 소개",
        "index_button_schedule" : "(일본어)상영 시간표",
        "index_button_exhibit" : "(일본어)예술 미디어스케이프",
        "index_button_exhibit_sub" : " ",
        "index_button_art_1" : "(일본어)동행 모먼트서울",
        "index_button_art_1_sub" : " ",
        "index_button_art_2" : "(일본어)매력 한강네이처",
        "index_button_art_2_sub" : " ",
        
        "back_button_text" : "BACK",
        "top_button_text" : "(일본어)Top",
        "list_button_text" : "list",
        "prev_button_text" : "(일본어)이전",
        "next_button_text" : "(일본어)다음",

        "schedule_explain_name" : "(일)아뜰리에노들 미디어아트 상영 시간표",
        "atelier_nodeul_name" : "(일본어)아뜰리에 노들",
        "atelier_nodeul_explain" : "(일본어)아뜰리에 노들 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "schedule_name" : "(일)작품명",
        "schedule_time" : "(일)상영 시간",

        "exhibit_title" : "(일본어)전시 소개",        
        "exhibit_introduce" : "(일본어)전시 소개\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        "exhibit_explain" : "(일본어)전시 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "link_button_text" : "(일본어)영상 보러가기",

        "exhibit_name_1" : "(일)예술: 미디어스케이프 (Mediascape)",
        "artist_name_1" : "(일본어)작가명1",
        "art_name_1" : "(일본어)작품명1",
        "art_explain_1" : "(일본어)작품 설명1\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_2" : "(일본어)전시명2",
        "artist_name_2" : "(일본어)작가명2",
        "art_name_2" : "(일본어)작품명2",
        "art_explain_2" : "(일본어)작품 설명2\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_3" : "(일본어)전시명3",
        "artist_name_3" : "(일본어)작가명3",
        "art_name_3" : "(일본어)작품명3",
        "art_explain_3" : "(일본어)작품 설명3\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",

        "directions_explain" : "(일)지하철\n1호선\n용산역 하차 - 도보 약 300m 위치의 신용산역 정류장(03-004) 노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n4호선\n신용산역 3번 출구 - 도보 100m 위치 신용산역 정류장(03-004) 용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동\n\n\n\n버스\n간선 버스\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752\n\n자선 버스\n6211"
    }
    
}
