const translations = {
    ko: {
        "index_button_introduce" : "아뜰리에 노들 소개",
        "index_button_schedule" : "상영 시간표",
        "index_button_exhibit" : "예술 미디어스케이프",
        "index_button_exhibit_sub" : "Mediascape",
        "index_button_art_1" : "동행 모먼트서울",
        "index_button_art_1_sub" : "Moment Seoul",
        "index_button_art_2" : "매력 한강네이처",
        "index_button_art_2_sub" : "Hangang Nature",
        "index_button_directions" : "오시는 길",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        "atelier_nodeul_name" : "아뜰리에 노들",
        "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<아들리에 노들 개장전시> 상영 시간표",
        "schedule_explain_date" : "전시 기간 | 2025.11.28.(금) ~ 2026.02.28.(토)",
        "schedule_explain_pos" : "상영 장소 | 노들섬 남단 한강대교 교각 하부 미디어파사드",
        "schedule_explain_pos_detail" : "노들섬 아트라운지 미디어볼 상명 시간",
        "schedule_explain_time" : "상명 시간 | 17:00 ~ 22:00",
        "schedule_explain_time_detail" : "(매 시각 정시 상영)",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        "exhibit_intro_title" : "전시 소개",        
        "exhibit_introduce_name" : "아뜰리에 노들 개장전시",
        "exhibit_introduce" : "토마스 헤더윅의 <소리풍경(Soundscape)> 착공과 함께\n[아뜰리에 노들]의 개장 전시가 시작됩니다.\n\n전시는 예술, 동행, 매력 세 가지 섹션으로 구성됩니다.\n\n먼저, ‘미디어 스케이프’ 섹션에서는 3명의 미디어\n아티스트(서효정, 양민하, 정윤수)가 선보이는 예술적인\n미감을 경험할 수 있으며,\n‘모먼트 서울’ 섹션에서는 <하루 끝 감성 메시지>와 서울\n명소를 소개하는 <해치와 서울 나들이>를 통해 서울의\n일상과 정서를 느낄 수 있습니다.\n‘한강 네이처’ 섹션에서는 한강의 생태를 미디어아트로\n풀어낸 작품들을 만나볼 수 있습니다.\n\n• 예술: 미디어 스케이프 (Media Scape)\n• 동행: 모먼트 서울 (Moment Seoul)\n• 매력: 한강 네이처 (Hangang Nature)",
        "exhibit_explain_name_1" : "미디어스케이프",
        "exhibit_explain_1" : "‘미디어 스케이프 (Media Scape)’는 도시의 빛과 물결이\n교차하는 한강 노들섬에서 펼쳐지는 미디어아트 전시입니다.\n\n미디어 아티스트 서효정, 양민하, 정윤수는 각기 다른\n시각으로 서울과 노들섬의 리듬, 감각, 에너지를 표현합니다.\n\n빛과 예술이 한강의 표면을 따라 흐르며, 노들섬의 예술적\n매력과 한강의 새로운 가능성을 함께 보여줍니다.",
        "exhibit_explain_name_2" : "모먼트서울",
        "exhibit_explain_2" : "모먼트 서울 (Moment Seoul)’은 서울의 핵심 가치인 '약자와\n동행하는 상생 도시'를 강조합니다.\n\n서울의 상징인 해치가 서울의 명소를 돌아보며 도시의 풍경과\n일상을 선보이고, 하루의 끝, 지친 시민들에게 감성 메시지를\n통해 위로와 응원의 온기를 전달합니다.",
        "exhibit_explain_name_3" : "한강 네이처",
        "exhibit_explain_3" : "‘한강 네이처 (Hangang Nature)’는 서울의 비전인 ‘매력’을\n상징하며, 자연이 살아 숨 쉬는 한강의 생태를 미디어아트로\n풀어낸 자연도감입니다.\n\n한강과 노들섬의 생태를 통해 자연의 숨결을 조명하며,\n매력 도시 서울과 한강의 진면목을 선보입니다. ",
        
        "link_button_text" : "영상 보러가기",

        "exhibit_name_1" : "예술\n미디어스케이프\n(Mediascape)",        
        "exhibit_name_2" : "동행\n모먼트서울\n(Moment Seoul)",        
        "exhibit_name_3" : "매력\n한강 네이쳐\n(Hangang Nature)",

        "art_name_1" : "작품명1",
        "art_name_2" : "작품명2",
        "art_name_3" : "작품명3",
        
        "exhibit_list_1" : "물에 비친 섬",
        "exhibit_list_2" : "코드로 짜인 풍경 : 서울",
        "exhibit_list_3" : "묵상2025",
        "exhibit_list_4" : "심연",
        "exhibit_list_5" : "후라칸",
        "exhibit_list_6" : "로즐린",
        "exhibit_list_7" : "하루 끝 감성메세지",
        "exhibit_list_8" : "해치의 서울 나들이",
        "exhibit_list_9" : "노들의 이야기",

        "art_list_1" : "물에 비친 섬",
        "art_list_2" : "코드로 짜인 풍경 : 서울",
        "art_list_3" : "묵상2025",
        "art_list_4" : "심연",
        "art_list_5" : "후라칸",
        "art_list_6" : "로즐린",
        "art_list_7" : "하루 끝 감성메세지",
        "art_list_8" : "해치의 서울 나들이",
        "art_list_9" : "노들의 이야기",

        "artist_name_1" : "서효정",
        "artist_name_2" : "서효정",
        "artist_name_3" : "양민하",
        "artist_name_4" : "양민하",
        "artist_name_5" : "정윤수",
        "artist_name_6" : "정윤수",
        "artist_name_7" : "",
        "artist_name_8" : "",
        "artist_name_9" : "",

        "art_explain_1" : "노들섬이라는 장소의 고유성을 기반으로, 한강물에 비친\n풍경과 섬의 생태(물고기, 새, 식물 등)에서 추상적 모티프를\n채집하여 만든 작품이다.\n\n작가는 자연의 형태와 움직임을 기하학적인 도형으로\n패턴화하여, 미디어 파사드의 벽과 바닥을 몰입적인 프로젝션\n환경으로 구현하였다.\n\n이는 토마스 헤더윅이 제안한 ‘도시 속에서 잠시 벗어나\n몰입과 탐험을 가능하게 하는 장소’라는 섬의 개념과\n공명하며, 기하학적 추상 미디어 풍경으로 재탄생한다.",
        "art_explain_2" : "서울이라는 도시 풍경을 데이터와 코드의 언어로 엮어, 태피스트리의 직조 방식처럼 디지털 알고리즘으로 재해석하여\n시각화한 작품이다.\n\n도시 보행자의 흐름, 차량의 이동, 역동적으로 구성된 건축\n구조 등 서울의 다양한 움직임을 직물을 짜듯 여러 리듬으로\n재구성하였다.\n\n서울이 지닌 질서와 변화, 에너지는 씨실과 날실의 반복과\n변주를 통해 추상적이면서도 아름다운 디지털 풍경이 된다.",
        "art_explain_3" : "<묵상 2025>는 빛의 파동과 이미지의 적층, 반복되는 시각적\n패턴을 통해 '도시 명상'의 가능성을 탐구하는 작품이다.\n\n소리와 함께 발산하는 파장은 마치 명상을 하듯 대자연 속\n인간의 존재를 사유하게 만든다.\n\n\"우리는 소리와 이미지를 통해 사유하는 시청각적 상징의\n장소에 존재하며, 복합적인 감정과 사고의 순환 속에서\n멈추고, 바라보고, 사유한다.\"",
        "art_explain_4" : "<심연>은 빛과 어둠, 입구와 출구, 질서와 혼란 등 세 가지\n상반된 개념을 수학적 알고리즘을 통해 하나로 연결하는\n작품이다.\n\n흑과 백, 비어있음과 꽉 참, 색상 변화의 시퀀스는 교차적인\n움직임을 통해 자연스럽게 하나의 작품을 이룬다.\n\n마치 심연의 깊이를 가늠할 수 없듯, 다름과 차이는 사유의\n영역에서 시작된다는 것을 깨닫게 한다.",
        "art_explain_5" : "<후라칸>은 스페인어로 ‘바람’, ‘허리케인’, ‘폭풍’을 뜻하는\n단어로, 작품은 거대한 입자의 알고리즘의 통해 수십만 개의\n파티클 소용돌이는 선보이는 작품이다.\n\n화면 중앙 고요한 태풍의 눈을 중심으로 소리와 바람에 의해\n얽히고 흩어지며, 자연의 폭풍처럼 휘몰아치며 힘의 응축과\n충돌, 균형을 선보인다.",
        "art_explain_6" : "<로즐린>은 자신의 감정을 투영할 수 있는 아름다운 존재를\n은유적으로 표현한 작품이다.\n\n작품에는 기억의 잔향과 자연의 색채를 담아 디지털 시각\n추상으로 풀어냈다.\n\n꽃이 피듯 몽글몽글한 감정의 이미지는 생성과 소멸의\n파티클, 노이즈 알고리즘을 통해 섬에서 강으로, 다시 폭포로\n이어지며 대자연의 풍경으로 변화한다.",
        "art_explain_7" : "하루를 마무리하는 시민들에게 위로와 응원의 메시지를\n전달한다.\n\n\"걸음을 멈춰도 괜찮다고 바람이 먼저 말해주는 곳, 오늘\n당신에게도 그런 쉼이 필요합니다. 서울시가 응원합니다.\"",
        "art_explain_8" : "해치와 친구들이 서울의 명소를 소개한다.\n\n지하철과 한강 버스를 타고 출퇴근하며, 광화문과 한강을\n오가며, 노들섬에 도착하여 미디어 파사드 작품을 관람한다. ",
        "art_explain_9" : "바람과 물결, 생명의 빛이 살아 숨 쉬는 노들섬은 나무와 새,\n물고기가 노니는 아름다운 자연이 된다.",

        "time_table_title" : "전시 순서 안내",
        "time_table_title_1" : "예술",
        "time_table_title_2" : "동행",
        "time_table_title_3" : "매력",
        "time_table_title_sub_1" : "미디어 스케이프",
        "time_table_title_sub_2" : "모먼트 서울",
        "time_table_title_sub_3" : "한강 네이처",
        "time_table_art_1" : "1. 서효정 <물에 비친 섬>",
        "time_table_art_2" : "2. 양민하 <묵상2025>",
        "time_table_art_3" : "3. 정윤수 <후라칸> ",
        "time_table_art_4" : "4. 하루 끝 감성메세지",
        "time_table_art_5" : "5. 해치와 서울나들이",
        "time_table_art_6" : "6. 노들의 이야기 ",
        "time_table_art_7" : "7. 서효정 <코드로 짜인 풍경:서울>",
        "time_table_art_8" : "8. 양민하 <심연>",
        "time_table_art_9" : "9. 정윤수 <로즐린> ",
        "time_table_art_10" : "10. 하루 끝 감성메세지 ",
        "time_table_art_11" : "11. 해치와 서울나들이",
        "time_table_art_12" : "12. 노들의 이야기 ",

        "directions_title" : "오시는 길",

        "directions_explain_title_1" : "지하철",
        "directions_explain_title_2" : "버스",
        "directions_explain_title_3" : "자선 버스",

        "directions_explain_1" : "1호선\n용산역 5번출구 하차 - 도보 약 300m 위치의 신용산역\n정류장(03-004)\n노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n4호선\n신용산역 3번출구 - 도보 100m 위치 신용산역 정류장(03-004)\n용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동\n\n\n",
        "directions_explain_2" : "간선 버스\n150, 151, 152, 500, 504, 506,\n507, 605, 750A, 750B, 751, 752",
        "directions_explain_3" : "지선버스\n6211\n\n한강버스\n여의도 - 압구정 사이 구간에서 관람 가능",
    },
    en : {
        "index_button_introduce" : "Atelier Nodeul Introduction",
        "index_button_schedule" : "Schedule",
        "index_button_exhibit" : "Art Media Scape",
        "index_button_exhibit_sub" : " ",
        "index_button_art_1" : "Harmony Moment Seoul",
        "index_button_art_1_sub" : " ",
        "index_button_art_2" : "Charm Hangang Nature",
        "index_button_art_2_sub" : " ",
        "index_button_directions" : "Location",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        "atelier_nodeul_name" : "아뜰리에 노들",
        "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<Atelier Nodeul Opening Exhibition> Timeline",
        "schedule_explain_date" : "Exhibition Period | November 28, 2025 (Fri) – February 28, 2026 (Sat)",
        "schedule_explain_pos" : "Venue  | Media Façade under the southern pier of Hangang Bridge, \n               Nodeul Island",
        "schedule_explain_pos_detail" : "",
        "schedule_explain_time" : "Screening Hours | 17:00–22:00",
        "schedule_explain_time_detail" : "(on the hour, every hour)",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        "exhibit_intro_title" : "Exhibition Introduction",        
        "exhibit_introduce_name" : "Atelier Nodeul Opening Exhibition",
        "exhibit_introduce" : "With the groundbreaking of Thomas Heatherwick’s <Soundscape>, the opening exhibition of [Atelier\nNodeul] begins.\nThe exhibition is composed of three sections: Art,\nHarmony, and Charm.\n\nIn the “Media Scape” section, visitors can experience\nthe artistic sensibilities of three media artists\n(SEOHYO, Yang Minha, and Joung Yunsu).\nThe “Moment Seoul” section presents <End-of-Day\nEncouragement> and <Seoul Outing With Hechi>\nJourney, offering a glimpse into the everyday emotions and scenery of the city.\nFinally, the “Hangang Nature” section showcases\nmedia art works inspired by the ecological landscapes\nof the Hangang River.\n\n• Art: Media Scape\n• Harmony: Moment Seoul\n• Charm: Hangang Nature",
        "exhibit_explain_name_1" : "Media Scape",
        "exhibit_explain_1" : "'Media Scape' is a media art exhibition presented on\nNodeul Island, where the lights and ripples of the city\nintersect along the Hangang River.\nMedia artists SEOHYO, Yang Minha, and Joung Yunsu each\ninterpret the rhythms, sensibilities, and energy of Seoul\nand Nodeul Island through their own unique perspectives.\nAs light and art flow across the surface of the river, the\nexhibition reveals both the artistic charm of Nodeul Island\nand the new possibilities held within the Hangang River.",
        "exhibit_explain_name_2" : "Moment Seoul",
        "exhibit_explain_2" : "'Moment Seoul' highlights one of Seoul’s core values: a\ncompassionate city that walks alongside the vulnerable.\nSeoul’s symbolic guardian, Hechi, travels through the city’s\nlandmarks, presenting scenes of everyday urban life.\nAt the end of a long day, the work delivers messages of\ncomfort and encouragement to weary citizens, offering\nwarmth and emotional support.",
        "exhibit_explain_name_3" : "Hangang Nature",
        "exhibit_explain_3" : "'Hangang Nature' represents Seoul’s vision of 'Charm',\npresenting a media-art interpretation of the living ecology\nof the Hangang River.\nThrough the natural life found in the Hangang and on\nNodeul Island,\nthe exhibition highlights the breath of nature and reveals\nthe true character of both the river and Seoul as a city of\ncharm.",
        
        "link_button_text" : "Watch Video",

        "exhibit_name_1" : "Art\nMedia Scape",
        "exhibit_name_2" : "Harmony\nMoment Seoul",
        "exhibit_name_3" : "Charm\nHangang Nature",

        "art_name_1" : "작품명1",
        "art_name_2" : "작품명2",
        "art_name_3" : "작품명3",
        
        "exhibit_list_1" : "Reflected Island",
        "exhibit_list_2" : "Coded Tapestry: Seoul",
        "exhibit_list_3" : "Meditation 2025",
        "exhibit_list_4" : "Abyss",
        "exhibit_list_5" : "Huracan",
        "exhibit_list_6" : "Roslyn",
        "exhibit_list_7" : "End-of-Day Encouragement",
        "exhibit_list_8" : "Seoul Outing With Hechi",
        "exhibit_list_9" : "The Story of The Nodeul",

        "art_list_1" : "Reflected Island",
        "art_list_2" : "Coded Tapestry:\nSeoul",
        "art_list_3" : "Meditation 2025",
        "art_list_4" : "Abyss",
        "art_list_5" : "Huracan",
        "art_list_6" : "Roslyn",
        "art_list_7" : "End-of-Day\nEncouragement",
        "art_list_8" : "Seoul Outing With\nHechi",
        "art_list_9" : "The Story of The\nNodeul",

        "artist_name_1" : "SEOHYO",
        "artist_name_2" : "SEOHYO",
        "artist_name_3" : "Yang Minha",
        "artist_name_4" : "Yang Minha",
        "artist_name_5" : "Jung Yunsu",
        "artist_name_6" : "Jung Yunsu",
        "artist_name_7" : "",
        "artist_name_8" : "",
        "artist_name_9" : "",

        "art_explain_1" : "Based on the unique identity of Nodeul Island, this work\ngathers abstract motifs from the reflections on the\nHangang River and the island’s ecology (fish, birds,\nplants, and more).\n\nThe artist reinterprets natural forms and movements as\ngeometric patterns, transforming the media façade’s\nwalls and floor into an immersive projection\nenvironment.\n\nIn resonance with Thomas Heatherwick’s concept of the\nisland as a place for immersion and exploration within\nthe city, the work is reborn as a geometric abstract\nmedia landscape.",
        "art_explain_2" : "This work visualizes the urban landscape of Seoul by weaving it through the language of data and code, digitally reinterpreting the weaving techniques of tapestry through algorithmic structures.\n\nThe flows of pedestrians, the movement of vehicles, and the dynamic compositions of architecture are\nre-organized into rhythmic patterns, as if weaving multiple threads into fabric.\n\nThrough repeated and varied interplays of warp and weft, Seoul’s order, change, and energy transform into an abstract yet beautiful digital landscape.",
        "art_explain_3" : "<Meditation2025> explores the possibility of urban meditation through waves of light, layered imagery, and repeating visual patterns.\n\nThe vibrations emitted alongside sound invite viewers to contemplate human existence within the vastness of nature, as if entering a meditative state.\n\n“We exist in audiovisual symbolic spaces where thought is shaped through sound and image,\nand within the circulation of complex emotions and ideas, we pause, observe, and contemplate.”",
        "art_explain_4" : "<Abyss> connects three opposing concepts like  light and darkness, entrance and exit, order and chaos, through mathematical algorithms.\n\nSequences of black and white, emptiness and fullness, and shifting colors intersect and flow together, naturally forming a single unified work.\n\nJust as the depth of an abyss cannot be measured, the piece reveals that difference and contrast originate from the realm of contemplation.",
        "art_explain_5" : "<Huracán> (a Spanish word meaning wind, hurricane, or storm) presents swirling masses of hundreds of thousands of particles generated through a grand algorithmic system.\n\nAround the calm eye of the storm at the center of the screen, sound and wind intertwine and scatter, unleashing movements that mirror the force of a natural tempest and revealing moments of tension, collision, and balance.",
        "art_explain_6" : "<Roslyn> is a work that metaphorically represents a beautiful being onto which personal emotions can be projected.\n\nIt captures the lingering resonance of memory and the colors of nature, rendered through digital visual abstraction.\n\nLike a blooming flower, its soft, budding emotional imagery moves through particles of creation and dissolution and noise-based algorithms, flowing from the island to the river and eventually cascading into a grand natural landscape.",
        "art_explain_7" : "It delivers messages of comfort and encouragement to citizens as they end their day.\n\n“Where the breeze gently tells you it’s okay to pause, may you also find a moment of rest today. The City of Seoul is cheering for you.”",
        "art_explain_8" : "Hechi and his friends introduce the landmarks of Seoul.\n\nThey commute by subway and Hangang Bus, travel between Gwanghwamun and the Hangang River, and eventually arrive at Nodeul Island to view the media façade exhibition.",
        "art_explain_9" : "Nodeul Island, alive with wind, waves, and the light of life becomes a beautiful natural landscape where trees, birds, and fish thrive.",

        "time_table_title" : "Information",
        "time_table_title_1" : "Art",
        "time_table_title_2" : "Harmony",
        "time_table_title_3" : "Charm",
        "time_table_title_sub_1" : "Media Scape ",
        "time_table_title_sub_2" : "Moment Seoul",
        "time_table_title_sub_3" : "Hangang Nature",
        "time_table_art_1" : "1. SEOHYO <Reflected Island>",
        "time_table_art_2" : "2. Yang Minha <Meditation2025>",
        "time_table_art_3" : "3. Joung Yunsu <Huracán> ",
        "time_table_art_4" : "4. End-of-Day Encouragement ",
        "time_table_art_5" : "5. Seoul Outing With Hechi ",
        "time_table_art_6" : "6. The Story of The Nodeul ",
        "time_table_art_7" : "7. SEOHYO <Coded Tapestry: Seoul>",
        "time_table_art_8" : "8. Yang Minha <Abyss> ",
        "time_table_art_9" : "9. Joung Yunsu <Roslyn>",
        "time_table_art_10" : "10. End-of-Day Encouragement",
        "time_table_art_11" : "11. Seoul Outing With Hechi",
        "time_table_art_12" : "12. The Story of The Nodeul ",

        "directions_title" : "Location",

        "directions_explain_title_1" : "Subway",
        "directions_explain_title_2" : "Bus",
        "directions_explain_title_3" : "Green Bus (Local Route)",

        "directions_explain_1" : "Line 1\nYongsan Station – Exit 5 → Walk about 300m to Yongsan Station\nBus Stop (03-004) → Take a bus toward Nodeul Island → Get off at\nNodeul Island Stop (03-340)\n\nLine 4\nSinyongsan Station – Exit 3 → Walk 100m to Sinyongsan Station\nBus Stop (03-004) → Take a bus toward Yongsan / Nodeul Island →\nContinue toward Hangang Bridge for about 700m\n\nLine 9\nNodeul Station – Exit 2 → Walk approximately 700m toward\nHangang Bridge\n",
        "directions_explain_2" : "Blue Bus (Main Routes)\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752",
        "directions_explain_3" : "6211\n\nHangang Bus\nThe exhibition is visible while riding between Yeouido and Apgujeong.",
    },
    ja : {
        "index_button_introduce" : "(일본어)아뜰리에 노들 소개",
        "index_button_schedule" : "(일본어)상영 시간표",
        "index_button_exhibit" : "(일본어)예술 미디어스케이프",
        "index_button_exhibit_sub" : " ",
        "index_button_art_1" : "(일본어)동행 모먼트서울",
        "index_button_art_1_sub" : " ",
        "index_button_art_2" : "(일본어)매력 한강네이처",
        "index_button_art_2_sub" : " ",
        
        "back_button_text" : "BACK",
        "top_button_text" : "(일본어)Top",
        "list_button_text" : "list",
        "prev_button_text" : "(일본어)이전",
        "next_button_text" : "(일본어)다음",

        "schedule_explain_name" : "(일)아뜰리에노들 미디어아트 상영 시간표",
        "atelier_nodeul_name" : "(일본어)아뜰리에 노들",
        "atelier_nodeul_explain" : "(일본어)아뜰리에 노들 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "schedule_name" : "(일)작품명",
        "schedule_time" : "(일)상영 시간",

        "exhibit_title" : "(일본어)전시 소개",        
        "exhibit_introduce" : "(일본어)전시 소개\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        "exhibit_explain" : "(일본어)전시 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "link_button_text" : "(일본어)영상 보러가기",

        "exhibit_name_1" : "(일)예술: 미디어스케이프 (Mediascape)",
        "artist_name_1" : "(일본어)작가명1",
        "art_name_1" : "(일본어)작품명1",
        "art_explain_1" : "(일본어)작품 설명1\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_2" : "(일본어)전시명2",
        "artist_name_2" : "(일본어)작가명2",
        "art_name_2" : "(일본어)작품명2",
        "art_explain_2" : "(일본어)작품 설명2\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_3" : "(일본어)전시명3",
        "artist_name_3" : "(일본어)작가명3",
        "art_name_3" : "(일본어)작품명3",
        "art_explain_3" : "(일본어)작품 설명3\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",

        "directions_explain" : "(일)지하철\n1호선\n용산역 하차 - 도보 약 300m 위치의 신용산역 정류장(03-004) 노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n4호선\n신용산역 3번 출구 - 도보 100m 위치 신용산역 정류장(03-004) 용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동\n\n\n\n버스\n간선 버스\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752\n\n자선 버스\n6211"
    }
    
}
