const translations = {
    ko: {
        "index_button_introduce" : "아뜰리에 노들 소개",
        "index_button_schedule" : "상영 시간표",
        "index_button_exhibit" : "예술 미디어스케이프",
        "index_button_exhibit_sub" : "Mediascape",
        "index_button_art_1" : "동행 모먼트서울",
        "index_button_art_1_sub" : "Moment Seoul",
        "index_button_art_2" : "매력 한강네이처",
        "index_button_art_2_sub" : "Hangang Nature",
        "index_button_directions" : "오시는 길",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        "atelier_nodeul_name" : "아뜰리에 노들",
        "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<아들리에노들> 미디어아트 상영 시간표",
        "schedule_explain_date" : "전시 기간 | 2025.11.01~ 2025.12.15",
        "schedule_explain_pos" : "상영 장소 | 노들섬 아트라운지 미디어볼",
        "schedule_explain_pos_detail" : "노들섬 아트라운지 미디어볼 상명 시간",
        "schedule_explain_time" : "상명 시간 | 매일 11:00~ 21:00",
        "schedule_explain_time_detail" : "(10분 간격 순환 상영)",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        "exhibit_intro_title" : "전시 소개",        
        "exhibit_introduce_name" : "아뜰리에 노들 개장전시",
        "exhibit_introduce" : "토마스헤더웍의 <소리풍경(Soundscape)> 착공을\n기념하여, 노들섬 남단 교각 하부에서 미디어 파사드를\n선보입니다.\n3명의 미디어아트 작가들 (서효정• 양민하•정윤수)의\n창의적 해석으로 색을 입힌 노들섬 만의\n미디어스케이프'를 비롯하여 '모먼트 서울, 한강 네이처'등\n서울을 대표하는 [예술, 동행, 매력]을 상징하는 콘텐츠들을\n즐기실 수 있습니다.\n\n• 예술 콘텐츠: 미디어 스케이프(Media scape)\n• 동행 콘텐츠: 모먼트 서울(Moment Seoul)\n• 매력 콘텐츠: 한강 네이처(Hangang Nature)\n",
        "exhibit_explain_name_1" : "미디어스케이프",
        "exhibit_explain_1" : "미디어스케이프는 도시의 빛과 물결이 교차하는 한강의\n노들섬에서 펼쳐지는 미디어아트 전시입니다.\n미디어아티스트 서효정, 양민하, 정윤수 작가가 함께 참여하여\n각기 다른 시선으로 도시의 리듬과 감각, 그리고 서울의\n에너지를 표현합니다.\n빛과 영상이 한강의 표면을 따라 흘러가며 노들섬이 가진\n매력과 한강이 품은 새로운 가능성을 함께 보여줍니다.",
        "exhibit_explain_name_2" : "모먼트서울",
        "exhibit_explain_2" : "모먼트서울은 서울시의 가치인 '약자와 동행하는 상생도시'를\n이야기합니다.\n지친 몸을 이끌고 집으로 떠나는 퇴근길.\n서울의 상징인 해치가 시민들과 함께 서울 곳곳을 거닐며\n그들의 하루에 위로를 건냅니다.\n빠르게 흐르는 도시의 속도 속에서 함께 살아가는 시민들에게,\n서울시가 감사한 마음과 동행의 따듯한 온도를 전합니다.",
        "exhibit_explain_name_3" : "한강 네이처",
        "exhibit_explain_3" : "한강네이처는 서울시의 비전인 '매력'을 상징하며, 자연이\n살아 숨쉬는 한강의 모습을 미디어로 표현한 전시입니다.\n도심 속에서도 자연의 호흡을 느낄 수 있는 영상을 통해\n매력적인 서울의 얼굴을 보여줍니다.\n도시의 소음과 빛 속에서 자연이 리듬을 되찾는 순간,\n한강과 노들섬의 숨결, 그리고 그 속의 생명력을 시민들에게\n전해집니다.",
        
        "link_button_text" : "영상 보러가기",

        "exhibit_name_1" : "예술\n미디어스케이프\n(Mediascape)",        
        "exhibit_name_2" : "동행\n모먼트서울\n(Moment Seoul)",        
        "exhibit_name_3" : "매력\n한강 네이쳐\n(Hangang Nature)",

        "art_name_1" : "작품명1",
        "art_name_2" : "작품명2",
        "art_name_3" : "작품명3",
        
        "exhibit_list_1" : "물에 비친 섬",
        "exhibit_list_2" : "Coded Tapestry: Seoul",
        "exhibit_list_3" : "심연",
        "exhibit_list_4" : "묵상2025",
        "exhibit_list_5" : "로즐린",
        "exhibit_list_6" : "후라칸",
        "exhibit_list_7" : "하루 끝 감성메세지",
        "exhibit_list_8" : "해치의 서울 나들이",
        "exhibit_list_9" : "노들의 이야기",

        "artist_name_1" : "서효정",
        "artist_name_2" : "서효정",
        "artist_name_3" : "양민하",
        "artist_name_4" : "양민하",
        "artist_name_5" : "정윤수",
        "artist_name_6" : "정윤수",
        "artist_name_7" : "",
        "artist_name_8" : "",
        "artist_name_9" : "",

        "art_explain_1" : "노들섬의 풍경과 생태에서 얻은 모티브를 기하학적\n패턴으로 재구성한 미디어파사드 작품이다.\n자연과 도시의 감각이 어우러진 새로운 기하학적 미디어\n풍경을 구현한다.",
        "art_explain_2" : "코드로 짜인 풍경: 서울\n서울의 도시 풍경을 데이터와 코드의 언어로 직조하듯\n시각화한 디지털 알고리즘 작품이다.\n보행자와 차량의 움직임과 역동적인 건축 구조 등을\n리듬으로 재구성해 서울의 질서와 에너지를 추상적\n디지털 풍경으로 표현한다.",
        "art_explain_3" : "<심연>은 빛과 어둠, 질서와 혼란 같은 상반된 갠며을\n수학적 알고리즘으로 연결한 작품이다.\n흑백의 대비와 색의 변주가 교차하며 하나의 흐름을\n 이루고, 다름과 차이가 사유에서 비롯됨을 깨닫게 한다.",
        "art_explain_4" : "<묵상 2025>는 빛의 파동과 이미지의 적층, 반복되는 패턴을 통해 '도시 명상'의 가능성을 탐구하는 작품이다.\n소리와 파장의 흐름 속에서 관람자는 명상하듯 멈추고\n 바라보며, 대자연 속 인간의 존재를 사유하게 된다.",
        "art_explain_5" : "<로즐린>은 기억의 잔향과 자연의 색채를 담아, 감정을\n투영할 수 있는 존재를 은유적으로 표현한 디지털 시각\n추상 작품이다.\n꽃이 피듯 몽글몽글한 감정의 이미지는 파티클과 노이즈\n알고리즘을 따라 섬에서 강, 그리고 폭포로 이어지며\n대자연의 풍경으로 확장된다.",
        "art_explain_6" : "<후라칸>은 '바람', '폭풍'을 뜻하는 이름처럼, 수십만 개\n파티클이 만든 소용돌이를 알고리즘으로 구현한 작품이다.\n태풍의 눈을 중심으로 소리와 바람이 얽히며 자연의 힘을\n빚어내는 응충과 균형을 보여준다.",
        "art_explain_7" : "하루를 마무리하는 시민들에게 위로와 응원의 메시지를\n전달한다.\n\"걸음을 멈춰도 괜찮다고 바람이 먼저 말해주는 곳. 오늘\n당신에게도 그런 쉼이 필요합니다. 서울시가 응원합니다.\"",
        "art_explain_8" : "해치와 친구들이 서우르이 명소를 소개한다.\n지하철과 한강버스를 타고 출퇴근하며, 광화문과 한강을\n오가며, 노들섬에 도착하여 미디어파사드 작품을\n관람한다.",
        "art_explain_9" : "바람과 물결, 생명의 빛이 살아 숨쉬는 노들섬은 나무와 새,\n물고기가 노니는 아름다운 자연이 된다.",

        "directions_title" : "오시는 길",

        "directions_explain_title_1" : "지하철",
        "directions_explain_title_2" : "버스",
        "directions_explain_title_3" : "자선 버스",

        "directions_explain_1" : "1호선\n용산역 5번출구 하차 - 도보 약 300m 위치의 신용산역\n정류장(03-004)\n노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n4호선\n신용산역 3번출구 - 도보 100m 위치 신용산역 정류장(03-004)\n용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동\n\n\n",
        "directions_explain_2" : "간선 버스\n150, 151, 152, 500, 504, 506,\n507, 605, 750A, 750B, 751, 752",
        "directions_explain_3" : "지선버스\n6211\n\n한강버스\n여의도 - 압구정 사이 구간에서 관람 가능",
    },
    en : {
        "index_button_introduce" : "Atelier Nodeul Introduction",
        "index_button_schedule" : "Screening Schedule",
        "index_button_exhibit" : "Art: Media Scape",
        "index_button_exhibit_sub" : "",
        "index_button_art_1" : "Companionship: Moment Seoul",
        "index_button_art_1_sub" : "",
        "index_button_art_2" : "Attraction: Hangang Nature",
        "index_button_art_2_sub" : "",
        "index_button_directions" : "Directions",
        
        "back_button_text" : "BACK",
        "top_button_text" : "Top",
        "list_button_text" : "list",
        "prev_button_text" : "이전",
        "next_button_text" : "다음",

        "atelier_nodeul_name" : "아뜰리에 노들",
        "atelier_nodeulPI_name" : "아뜰리에 노들 PI",
        "atelier_nodeul_explain" : "아뜰리에 노들을 한강대교 하단부에서 진행하는\n미디어파사드 전시를 의미합니다.\n노들섬 남단 교각 하부에 미디어 파사드 작품을\n전시하여 시민의 문화예술 향유의 경험을 확대하고,\n노들섬을 문화예술•관광의 관문 역할이자\n미디어아트 랜드마크를 조성하는 것에 목적을\n두고 있습니다.",
        "atelier_nodeulPI_explain" : "아뜰리에 노들의 PI는 노들섬의 물결과 프로젝션 영상의\n빛, 레이어, 파동에서 영감을 받아 탄생했습니다.\n한강의 흐름과 예술적 감각이 만나는 장면을 시각적으로\n형상화했으며, 다채로운 색상의 영상 작품이 상영되는\n미디어 파사드의 특성에 따라 각 전시마다 변화하는\n색상과 빛의 조합으로 유동적인 정체성을 표현합니다.",
        
        "schedule_explain_name" : "<Atelier Nodeul> Media Art Screening Schedule",
        "schedule_explain_date" : "Exhibition Period | 2025.11.01~ 2025.12.15",
        "schedule_explain_pos" : "Screening Venue | Media Wall, Nodeul Island Art Lounge",
        "schedule_explain_pos_detail" : "",
        "schedule_explain_time" : "Screening Hours | Daily 11:00 ~ 21:00",
        "schedule_explain_time_detail" : "(screened in 10 minute intervals)",

        "schedule_name" : "작품명",
        "schedule_time" : "상영 시간",

        "exhibit_intro_title" : "Exhibition Introduction",        
        "exhibit_introduce_name" : "Atelier Nodeul Opening Exhibition",
        "exhibit_introduce" : "To commemorate the groundbreaking,\nThomas Heatherwick's Soundscape will be presented\nas a special media facade under the southern bridge\npier of Nodeul Island.\nYou can also enjoy Media Scape-a work that captures\nthe artists' interpretations of Nodeul island from the\nperspectives of three media artists, Seo Hyojeong,\nYang Minha, and Jung Yoonsu-along with Moment\nSeoul and Hangang Nature, contents representing\nSeoul's Art, Companionship, and Attraction.",
        "exhibit_explain_name_1" : "Media Scape",
        "exhibit_explain_1" : "Media Scape is a media art exhibition unfolding on\nNodeul Island, where the lights and waves of the\ncity intersect along the Han River.\nMedia artists Seo Hyojeong, Yang Minha, and\nJung Yoonsu participate in the exhibition, each\nexpressing the rhythm, senses, and energy of Seoul\nthrough their own perspectives.\nLight and imagery flow along the surface of the\nHan River, revealing both the charm of Nodeul Island\nand the new possibilities carried by the river.",
        "exhibit_explain_name_2" : "Moment Seoul",
        "exhibit_explain_2" : "Moment Seoul tells the story of Seoul's value of\nbecoming a \"coexisting city that walks with the\nvulnerable.\"\nOn the way home after a tiring day, Haechi-Seoul's\nsymbolic guardian-walks through various parts of\nthe city with its citizens, offering comfort to their\neveryday moments.\nAmid the fast speed of urban life, Seoul conveys\ngratitude and the warm temperature of companionshi\nto the citizens living together.",
        "exhibit_explain_name_3" : "Hangang Nature",
        "exhibit_explain_3" : "Hangang Nature symbolizes Seoul's vision of\n\"Attraction,\" expressed through media art that\ncaptures the living nature of the Han River.\nThrough visuals that allow viewers to feel the breath\nof nature even within the city center, the work\nshowcases the attractive face of Seoul.\nIn the midst of the city's noise and lights, the\nmoments when nature regains its rhythm deliver\nthe breath of the Han River, the spirit of Nodeul\nIsland, and the life within them to the audience.",
        
        "link_button_text" : "Watch Video",

        "exhibit_name_1" : "Art\nMedia Scape",
        "exhibit_name_2" : "Companionship\nMoment Seoul",
        "exhibit_name_3" : "Attraction\nHangang Nature",

        "art_name_1" : "작품명1",
        "art_name_2" : "작품명2",
        "art_name_3" : "작품명3",
        
        "exhibit_list_1" : "Reflected Island",
        "exhibit_list_2" : "Coded Tapestry: Seoul",
        "exhibit_list_3" : "Abyss",
        "exhibit_list_4" : "Meditation 2025",
        "exhibit_list_5" : "Roslyn",
        "exhibit_list_6" : "Huracan",
        "exhibit_list_7" : "End-of-Day Encouragement",
        "exhibit_list_8" : "Seoul Outing With Hechi",
        "exhibit_list_9" : "The Story of The Nodeul",

        "artist_name_1" : "SEOHYO",
        "artist_name_2" : "SEOHYO",
        "artist_name_3" : "Yang Minha",
        "artist_name_4" : "Yang Minha",
        "artist_name_5" : "Jung Yoonsu",
        "artist_name_6" : "Jung Yoonsu",
        "artist_name_7" : "",
        "artist_name_8" : "",
        "artist_name_9" : "",

        "art_explain_1" : "A media facade work that reconstructs motifs drawn\nfrom Nodeul Island’s scenery and ecology into\ngeometric patterns.\nIt presents a new geometric media landscape where\nthe senses of nature and the city harmonize.",
        "art_explain_2" : "Code-Woven Landscape: Seoul\nThis digital algorithmic artwork visualizes Seoul’s\nurban scenery as if weaving it with the language of\ndata and code.\nBy reconstructing the movements of pedestrians and\nvehicles, as well as the dynamism of architectural\nstructures, into rhythmic patterns, it expresses the order\nand energy of Seoul as an abstract digital landscape.",
        "art_explain_3" : "<Abyss> connects contrasting concepts—such as light\nand darkness, order and chaos—through mathematical\nalgorithms.\nThe interplay of black-and-white contrasts and shifting\ncolor variations forms a single flow, reminding viewers\nthat differences and diversity originate from thought.",
        "art_explain_4" : "<Meditation 2025> explores the possibility of \“urban\nmeditation\” through light waves, layered imagery, and\nrepeated patterns.\nWithin the flow of sound and vibration, viewers pause\nand observe as if meditating, contemplating human\nexistence within the vastness of nature.",
        "art_explain_5" : "<Roslyn> metaphorically expresses an emotional,\nreflective presence through an abstract digital visual\nwork that contains the afterimage of memory and\nthe colors of nature.\nImages of soft emotions bloom like flowers, following\nparticle and noise algorithms from the island to the\nriver, and eventually to a waterfall—expanding into\na grand natural landscape.",
        "art_explain_6" : "<Huracan>—a name meaning \“wind\” and \“storm\”\n—implements vortexes created by hundreds of\nthousands of particles through algorithms.\nCentered around the eye of the storm, sound and\nwind intertwine, revealing the condensation and balance\nformed by the forces of nature.",
        "art_explain_7" : "It delivers a message of comfort and encouragement\nto citizens ending their day:\n\“On days when the wind tells you it’s okay to pause\nfirst, may you also find such rest today. The Seoul\nMetropolitan Government is cheering for you.\”",
        "art_explain_8" : "Haechi and friends introduce famous landmarks of Seoul.\nThey commute by subway and by Han River bus,\ntravel between Gwanghwamun and the Han River, and\narrive at Nodeul Island to view the media facade\nartworks.",
        "art_explain_9" : "Nodeul Island becomes a beautiful natural space where\nwind, waves, and the light of life breathe—filled with\ntrees, birds, and fish.",

        "directions_title" : "Directions",

        "directions_explain_title_1" : "Subway",
        "directions_explain_title_2" : "Bus",
        "directions_explain_title_3" : "Green Bus",

        "directions_explain_1" : "Line 1\nGet off at Yongsan Station Exit 5\n- Walk about 300m to Shinyongsan Station Bus Stop (03-004)\nTake a bus toward Nodeul Island\n- Get off at Nodeul Island Stop (03-340)\n\nLine 4\nShinyongsan Station Exit 3\n- Walk 100m to Shinyongsan Station Bus Stop (03-004)\nTake a bus toward Yongsan / Nodeul Island\n- Get off at Nodeul Island Stop (03-340)\n\nLine 9\nNodeul Station Exit 2\n- Walk approximately 700m toward Hangang Bridge\n",
        "directions_explain_2" : "Blue Bus Routes\n150, 151, 152, 500, 504, 506,\n507, 605, 750A, 750B, 751, 752",
        "directions_explain_3" : "6211\n\nHangang Bus\nViewable along the Yeouido–Apgujeong section of the route.",
    },
    ja : {
        "index_button_introduce" : "(일본어)아뜰리에 노들 소개",
        "index_button_schedule" : "(일본어)상영 시간표",
        "index_button_exhibit" : "(일본어)예술 미디어스케이프",
        "index_button_exhibit_sub" : " ",
        "index_button_art_1" : "(일본어)동행 모먼트서울",
        "index_button_art_1_sub" : " ",
        "index_button_art_2" : "(일본어)매력 한강네이처",
        "index_button_art_2_sub" : " ",
        
        "back_button_text" : "BACK",
        "top_button_text" : "(일본어)Top",
        "list_button_text" : "list",
        "prev_button_text" : "(일본어)이전",
        "next_button_text" : "(일본어)다음",

        "schedule_explain_name" : "(일)아뜰리에노들 미디어아트 상영 시간표",
        "atelier_nodeul_name" : "(일본어)아뜰리에 노들",
        "atelier_nodeul_explain" : "(일본어)아뜰리에 노들 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "schedule_name" : "(일)작품명",
        "schedule_time" : "(일)상영 시간",

        "exhibit_title" : "(일본어)전시 소개",        
        "exhibit_introduce" : "(일본어)전시 소개\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        "exhibit_explain" : "(일본어)전시 설명\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "link_button_text" : "(일본어)영상 보러가기",

        "exhibit_name_1" : "(일)예술: 미디어스케이프 (Mediascape)",
        "artist_name_1" : "(일본어)작가명1",
        "art_name_1" : "(일본어)작품명1",
        "art_explain_1" : "(일본어)작품 설명1\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_2" : "(일본어)전시명2",
        "artist_name_2" : "(일본어)작가명2",
        "art_name_2" : "(일본어)작품명2",
        "art_explain_2" : "(일본어)작품 설명2\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",
        
        "exhibit_name_3" : "(일본어)전시명3",
        "artist_name_3" : "(일본어)작가명3",
        "art_name_3" : "(일본어)작품명3",
        "art_explain_3" : "(일본어)작품 설명3\nㅁㅁ\nㅁㅁㅁ\nㅁㅁㅁㅁ",

        "directions_explain" : "(일)지하철\n1호선\n용산역 하차 - 도보 약 300m 위치의 신용산역 정류장(03-004) 노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n4호선\n신용산역 3번 출구 - 도보 100m 위치 신용산역 정류장(03-004) 용산-노들섬 방면 버스 탑승 - 노들섬 정류장(03-340) 하차\n\n9호선\n노들역 2번 출구 - 한강대교 방면으로 약 700m 이동\n\n\n\n버스\n간선 버스\n150, 151, 152, 500, 504, 506, 507, 605, 750A, 750B, 751, 752\n\n자선 버스\n6211"
    }
    
}
